name: MasterCI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Bucket actions
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm i
      - run: npm run test
      - run: npm run generate
      
      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./dist/*
          host: ${{ SECRESTs.SSH_HOST }}
          remote: ${{ SECRETS.SSH_SERVE }}
          port: ${{ SECRETS.SSH_PORT }}
          user: ${{ SECREST.SSH_USER }}
          key: ${{ SECRETS.SSH_KEY }}
